"""Centralized collection of icon identifiers used throughout the Streamlit UI."""

# icons
ICON_DELETE = ":material/delete:"
ICON_SAVE = ":material/save:"
ICON_ADD = ":material/add:"
ICON_EDIT = ":material/edit:"
ICON_BACK = ":material/arrow_back:"
ICON_CANCEL = ":material/cancel:"
ICON_LABEL = ":material/label:"
ICON_UPLOAD = ":material/upload:"
ICON_DOWNLOAD = ":material/download:"
ICON_REFRESH = ":material/refresh:"
ICON_RESULTS = ":material/bar_chart:"
ICON_COMMENT_ADD = ":material/add_comment:"
ICON_EXECUTE = ":material/play_arrow:"
ICON_ZIP = ":material/folder_zip:"
ICON_COMPARE = ":material/compare:"
ICON_DETAILS = ":material/search_insights:"
ICON_SELECT = ":material/check_box:"
ICON_UNSELECT = ":material/check_box_outline_blank:"
ICON_SEARCH = ":material/search:"
ICON_HELP = ":material/help:"
ICON_LINK = ":material/link:"
ICON_MAP = ":material/map:"
ICON_FILTER = ":material/filter_alt:"
ICON_CENTER_FOCUS_WEAK = ":material/center_focus_weak:"
